#!/bin/bash
#PBS -l nodes=1:ppn=1,pmem=1gb,pvmem=1gb
#PBS -l walltime=24:00:00
#PBS -N BATCH
#PBS -j oe
#PBS -M Jonathan.A.Gordon@uvm.edu
#PBS -m bea

# don't change this unless absolutely needed
DATE=`date +%m_%d_%Y`
#WD=$HOME/scratch/$PBS_JOBNAME"_"$DATE
WD=/users/j/a/jargordo/scratch/sequences/RNA_R2_08_15_2013/
if [ -d "$WD" ]
then
cd $WD
else
mkdir $WD
cd $WD
fi

FILES="$WD*.fastq"

for sample in $FILES; do
FILENAME=$(echo "$sample" | awk -F '/' '{print $9}')
ABRV_NAME=$(echo "$FILENAME" | awk -F '.' '{print $1}')

gzip $sample

done

echo "------------------------RUN_INFO----------------------------------"
echo "This is job ran on " `hostname` "on" `date +%d_%m_%Y_%H:%M:%S`



#Here's the command to connect VACC to COMIS (you run this from vacc)
#smbclient \\\\med23.med.uvm.edu\\Steinlab-Research$ --user=med\\yourID